### ISSUE TITLE
Seeking co-maintainers!

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/focus-group#12]
I've been shifting my focus away from UI development, so don't plan on addressing new issues myself. If you use this library and want to see development continue, you can make that happen by becoming a co-maintainer — with permissions to triage issues, merge PRs, cut releases, etc.

Please comment below if you're interested!

Another possibility is for a dedicated owner to fork this code and create a new package. I'd be happy to link to that library from the README of this one.

**Comment by shirshendubhowmick** [comment]
@davidtheclark Would like to take care of this repo too, as this is a dependecy of `react-aria-menubutton`

**Comment by spencervillars** [comment]
@davidtheclark I / my team is interested in maintaining this

**Comment by shirshendubhowmick** [comment]
@spencervillars This requirement is already closed.
