### ISSUE TITLE
Delegate document listener

### ISSUE THREAD

**Issue by souporserious** [davidtheclark/focus-group#3]
Do you think the document listener should be delegated? Then there is only one listener rather than a listener for every Focus Group. I can PR if you would like.

**Comment by davidtheclark** [comment]
Sure, PR would be fine. I think it's probably not too important, since I'd be surprised if there were many active focus groups at once. But if you can do it without adding significant complexity, we have nothing to lose.

**Comment by souporserious** [comment]
Sorry I'm dumb, you're right, there should be no reason to ever have multiple handlers running since you can just deactivate and reactivate when necessary.
