### ISSUE TITLE
Cannot assign to read only property 'keybindings' of object

### ISSUE THREAD

**Issue by souporserious** [davidtheclark/focus-group#7]
![image](https://cloud.githubusercontent.com/assets/2762082/19406291/17063c9e-9238-11e6-8d13-2ecdbc20bf62.png)
![image](https://cloud.githubusercontent.com/assets/2762082/19406293/23ca2fee-9238-11e6-833b-91bae3bfeaa8.png)

Found this error after doing a fresh NPM install. Any ideas to fix it?

Can we just use a local variable since we only use `options.keybindings` in the constructor?

**Comment by davidtheclark** [comment]
Yes, we could use a local variable. Call the argument `userOptions` and the variable `options`. I'm sort of confused by this, though —— I don't understand what's illegal about that unless you the user froze your options object. Is there something different about your environment that would make your options argument read only?

**Comment by souporserious** [comment]
Yeah it's weird. I'm not sure if my environment is doing it somewhere. I tried Googling around, but I couldn't find anything :/
